export const SETUP_USER = 'SETUP_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_RESPONSE = 'SIGNUP_USER_RESPONSE';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RESPONSE = 'LOGIN_USER_RESPONSE';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
